#---------------------------------------------------------------
# Configuraci贸n de la aplicaci贸n
#---------------------------------------------------------------
app_name: UENBGestor
app_version: 2.0
app_title: Sistema de gestion 
app_description: Sistema de Gesti贸n 
app_logo: /logo.png

#---------------------------------------------------------------
# Configuraci贸n de Cookies
#---------------------------------------------------------------
cookie:
  expiry_days: 30
  key: gestoria_cookies_key
  name: Gestor_cookie


credentials:
  usernames:
    Admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Administrador
      password: admin123
pre-authorized:
  emails:
    - melsby@gmail.com
table_color: Purples

#----------------------------------------------------------------------------
imgLogoPath: "/logo.png"
imgIconPath: "/logo.png"