app_description: "Sistema de Gesti\xF3n"
app_logo: /logo.png
app_name: UENBGestor
app_title: Sistema de gestion
app_version: 2.0
cookie:
  expiry_days: 30
  key: gestoria_cookies_key
  name: Gestor_cookie
credentials:
  cookie:
    expiry_days: 30
    key: some_secret_key
    name: some_cookie_name
  usernames:
    Admin:
      ID_ACCESO: admin_id
      coordinate: true
      email: admin@gmail.com
      failed_login_attempts: 0
      id_acceso: admin_id
      logged_in: false
      name: Administrador
      password: $2b$12$ukaiuGUoWBaHTgT5rvnmR.Zi4zvEtxyEvsoeHdCY1fdzzKpexk3du
      role: admin
      username: admin
    alexprofe:
      ID_ACCESO: 74d57e92-2f0a-4228-afe3-da230d8c8d67
      coordinate: false
      email: 1234423
      failed_login_attempts: 0
      id_acceso: 74d57e92-2f0a-4228-afe3-da230d8c8d67
      logged_in: false
      name: alex alex
      password: $2b$12$HS7KP8GRgsvrsc9Tnm7Vce2wR.p.gSnRjmx4lyNG1/wTCPa2En/zS
      role: profesor
      username: alexprofe
    joseprofe:
      ID_ACCESO: 611d70d2-ec90-4914-a608-0d0bfc9608df
      coordinate: true
      email: 2323
      failed_login_attempts: 0
      id_acceso: 611d70d2-ec90-4914-a608-0d0bfc9608df
      logged_in: false
      name: Jose Antonio Perez Diaz
      password: $2b$12$EcSk83ArcDtIZ9RQZUN.3.0.eIq2kFowiEAE8rdX6Z70Peyee47wW
      role: admin
      username: joseprofe
    zatanas:
      ID_ACCESO: 94a976a5-19f7-4af6-b3c3-b25778057639
      coordinate: false
      email: 644565
      failed_login_attempts: 0
      id_acceso: 94a976a5-19f7-4af6-b3c3-b25778057639
      logged_in: false
      name: zatanas gacial
      password: $2b$12$nXxwuluJhAflaQs7Npytmu76dOWpAeum2haX4ujPsZxFQaJoMQ25i
      role: profesor
      username: zatanas
imgIconPath: /logo.png
imgLogoPath: /logo.png
pre-authorized:
  emails:
  - melsby@gmail.com
roles:
  admin:
  - Dashboard
  - Calificaciones
  - Asistencias
  - Asistencias Del Personal
  - Personal
  - Estudiantes
  - Materias
  - Representantes
  - Rendimiento
  - Secciones
  - Grados
  - Parametros Generales
  estudiante:
  - Dashboard
  - Calificaciones
  - Asistencias
  - Representantes
  profesor:
  - Dashboard
  - Calificaciones
  - Asistencias
  - Asistencias Del Personal
  - Personal
  - Estudiantes
  - Materias
  - Representantes
  - Rendimiento
  - Secciones
  - Grados
  - Parametros Generales
  sin asignar: null
table_color: Purples
