app_description: "Sistema de Gesti\xF3n"
app_logo: /logo.png
app_name: UENBGestor
app_title: Sistema de gestion
app_version: 2.0
cookie:
  expiry_days: 30
  key: gestoria_cookies_key
  name: Gestor_cookie
credentials:
  cookie:
    expiry_days: 30
    key: some_secret_key
    name: some_cookie_name
  usernames:
    Admin:
      acceso_calificaciones: SI
      email: admin@gmail.com
      failed_login_attempts: 0
      id_acceso: admin_id
      logged_in: false
      name: Administrador
      password: $2b$12$ukaiuGUoWBaHTgT5rvnmR.Zi4zvEtxyEvsoeHdCY1fdzzKpexk3du
      role: admin
      username: admin
    alexprofe:
      email: 1234423
      failed_login_attempts: 0
      id_acceso: 74d57e92-2f0a-4228-afe3-da230d8c8d67
      logged_in: false
      name: alex alex
      password: $2b$12$HS7KP8GRgsvrsc9Tnm7Vce2wR.p.gSnRjmx4lyNG1/wTCPa2En/zS
      role: profesor
      username: alexprofe
imgIconPath: /logo.png
imgLogoPath: /logo.png
pre-authorized:
  emails:
  - melsby@gmail.com
roles:
  admin:
  - Dashboard
  - Calificaciones
  - Asistencias
  - Personal
  - Estudiantes
  - Materias
  - Representantes
  - Rendimiento
  - Secciones
  - Grados
  - Parametros Generales
  estudiante:
  - Dashboard
  - Calificaciones
  - Asistencias
  - Representantes
  profesor:
  - Dashboard
  - Calificaciones
  - Asistencias
  - Estudiantes
  - Representantes
  - Rendimiento
  sin asignar: null
table_color: Purples
