#---------------------------------------------------------------
# Configuración de la aplicación
#---------------------------------------------------------------
app_name: UENBGestor
app_version: 2.0
app_title: Sistema de gestion 
app_description: Sistema de Gestión 
app_logo: /logo.png

#---------------------------------------------------------------
# Configuración de Cookies
#---------------------------------------------------------------
cookie:
  expiry_days: 30
  key: gestoria_cookies_key
  name: Gestor_cookie


credentials:
  usernames:
    Admin:
      username: admin  # Agregado el campo 'username'
      email: admin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Administrador
      password: admin123  # Contraseña sin hash (puedes agregar un hash si es necesario)
      role: admin
    user1:
      username: user1
      email: admin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Administrador
      password: hashed_password
      role: estudiante  # Rol asignado
    user2:
      username: user2
      email: admin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Administrador
      password: hashed_password
      role: profesor
  cookie:
    name: some_cookie_name
    key: some_secret_key
    expiry_days: 30

roles:
  admin:
    - Dashboard
    - Calificaciones
    - Asistencias
    - Personal
    - Estudiantes
    - Materias
    - Representantes
    - Rendimiento
    - Secciones
    - Grados
  profesor:
    - Dashboard
    - Calificaciones
    - Asistencias
    - Estudiantes
    - Representantes
    - Rendimiento
  estudiante:
    - Dashboard
    - Calificaciones
    - Asistencias
    - Representantes
pre-authorized:
  emails:
    - melsby@gmail.com

table_color: Purples

#----------------------------------------------------------------------------
imgLogoPath: "/logo.png"
imgIconPath: "/logo.png"