app_description: "Sistema de Gesti\xF3n"
app_logo: /logo.png
app_name: UENBGestor
app_title: Sistema de gestion
app_version: 2.0
cookie:
  expiry_days: 30
  key: gestoria_cookies_key
  name: Gestor_cookie
credentials:
  cookie:
    expiry_days: 30
    key: some_secret_key
    name: some_cookie_name
  usernames:
    Admin:
      ID_ACCESO: admin_id
      coordinate: true
      email: admin@gmail.com
      failed_login_attempts: 0
      id_acceso: admin_id
      logged_in: false
      name: Administrador
      password: $2b$12$ukaiuGUoWBaHTgT5rvnmR.Zi4zvEtxyEvsoeHdCY1fdzzKpexk3du
      role: admin
      username: admin
imgIconPath: /logo.png
imgLogoPath: /logo.png
output_path: dependencias/plantillas/generadas/resultado.xlsx
plantilla_path: dependencias/plantillas/5- Enero 2023 -.xlsx
pre-authorized:
  emails:
  - melsby@gmail.com
roles:
  admin:
  - Dashboard
  - Calificaciones
  - Asistencias
  - Asistencias Del Personal
  - Personal
  - Estudiantes
  - Materias
  - Representantes
  - Rendimiento
  - Secciones
  - Grados
  - Parametros Generales
  sin asignar: null
table_color: Purples
