"""Initial migration

Revision ID: 9eccd674cdb6
Revises: 
Create Date: 2025-07-24 17:28:18.473899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eccd674cdb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ASIGNACION_EST_ID_SECCION_fkey'), 'ASIGNACION_EST', type_='foreignkey')
    op.drop_constraint(op.f('ASIGNACION_EST_ID_EST_fkey'), 'ASIGNACION_EST', type_='foreignkey')
    op.create_foreign_key(None, 'ASIGNACION_EST', 'ESTUDIANTES', ['ID_EST'], ['ID_EST'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'ASIGNACION_EST', 'SECCIONES', ['ID_SECCION'], ['ID_SECCION'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('ASISTENCIA_ESTUDIANTES_ID_SECCION_fkey'), 'ASISTENCIA_ESTUDIANTES', type_='foreignkey')
    op.drop_constraint(op.f('ASISTENCIA_ESTUDIANTES_ID_EST_fkey'), 'ASISTENCIA_ESTUDIANTES', type_='foreignkey')
    op.create_foreign_key(None, 'ASISTENCIA_ESTUDIANTES', 'SECCIONES', ['ID_SECCION'], ['ID_SECCION'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'ASISTENCIA_ESTUDIANTES', 'ESTUDIANTES', ['ID_EST'], ['ID_EST'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('ASISTENCIA_PROFESORES_ID_PROF_fkey'), 'ASISTENCIA_PROFESORES', type_='foreignkey')
    op.create_foreign_key(None, 'ASISTENCIA_PROFESORES', 'PROFESORES', ['ID_PROF'], ['ID_PROF'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('CALIFICACIONES_ID_EST_fkey'), 'CALIFICACIONES', type_='foreignkey')
    op.drop_constraint(op.f('CALIFICACIONES_ID_MATERIA_fkey'), 'CALIFICACIONES', type_='foreignkey')
    op.drop_constraint(op.f('CALIFICACIONES_ID_SECCION_fkey'), 'CALIFICACIONES', type_='foreignkey')
    op.create_foreign_key(None, 'CALIFICACIONES', 'SECCIONES', ['ID_SECCION'], ['ID_SECCION'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'CALIFICACIONES', 'ESTUDIANTES', ['ID_EST'], ['ID_EST'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'CALIFICACIONES', 'MATERIAS', ['ID_MATERIA'], ['ID_MATERIA'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('INCIDENCIAS_ID_PROF_fkey'), 'INCIDENCIAS', type_='foreignkey')
    op.drop_constraint(op.f('INCIDENCIAS_ID_EST_fkey'), 'INCIDENCIAS', type_='foreignkey')
    op.create_foreign_key(None, 'INCIDENCIAS', 'ESTUDIANTES', ['ID_EST'], ['ID_EST'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'INCIDENCIAS', 'PROFESORES', ['ID_PROF'], ['ID_PROF'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('FK_PROFESORES_ROLES'), 'PROFESORES', type_='foreignkey')
    op.create_foreign_key(None, 'PROFESORES', 'ROLES', ['ID_ROL'], ['ID_ROL'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('REPRE_EST_ID_REPRE_fkey'), 'REPRE_EST', type_='foreignkey')
    op.drop_constraint(op.f('REPRE_EST_ID_EST_fkey'), 'REPRE_EST', type_='foreignkey')
    op.create_foreign_key(None, 'REPRE_EST', 'ESTUDIANTES', ['ID_EST'], ['ID_EST'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'REPRE_EST', 'REPRESENTANTES', ['ID_REPRE'], ['ID_REP'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('SECCIONES_ID_GRADO_fkey'), 'SECCIONES', type_='foreignkey')
    op.drop_constraint(op.f('SECCIONES_ID_PROF_fkey'), 'SECCIONES', type_='foreignkey')
    op.create_foreign_key(None, 'SECCIONES', 'GRADOS', ['ID_GRADO'], ['ID_GRADOS'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'SECCIONES', 'PROFESORES', ['ID_PROF'], ['ID_PROF'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('SECCIONES_MATERIAS_ID_MATERIA_fkey'), 'SECCIONES_MATERIAS', type_='foreignkey')
    op.drop_constraint(op.f('SECCIONES_MATERIAS_ID_SECCION_fkey'), 'SECCIONES_MATERIAS', type_='foreignkey')
    op.create_foreign_key(None, 'SECCIONES_MATERIAS', 'SECCIONES', ['ID_SECCION'], ['ID_SECCION'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'SECCIONES_MATERIAS', 'MATERIAS', ['ID_MATERIA'], ['ID_MATERIA'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('TELEFONOS_REPRE_ID_REP_fkey'), 'TELEFONOS_REPRE', type_='foreignkey')
    op.create_foreign_key(None, 'TELEFONOS_REPRE', 'REPRESENTANTES', ['ID_REP'], ['ID_REP'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TELEFONOS_REPRE', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('TELEFONOS_REPRE_ID_REP_fkey'), 'TELEFONOS_REPRE', 'REPRESENTANTES', ['ID_REP'], ['ID_REP'], ondelete='CASCADE')
    op.drop_constraint(None, 'SECCIONES_MATERIAS', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'SECCIONES_MATERIAS', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('SECCIONES_MATERIAS_ID_SECCION_fkey'), 'SECCIONES_MATERIAS', 'SECCIONES', ['ID_SECCION'], ['ID_SECCION'], ondelete='CASCADE')
    op.create_foreign_key(op.f('SECCIONES_MATERIAS_ID_MATERIA_fkey'), 'SECCIONES_MATERIAS', 'MATERIAS', ['ID_MATERIA'], ['ID_MATERIA'], ondelete='CASCADE')
    op.drop_constraint(None, 'SECCIONES', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'SECCIONES', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('SECCIONES_ID_PROF_fkey'), 'SECCIONES', 'PROFESORES', ['ID_PROF'], ['ID_PROF'], ondelete='CASCADE')
    op.create_foreign_key(op.f('SECCIONES_ID_GRADO_fkey'), 'SECCIONES', 'GRADOS', ['ID_GRADO'], ['ID_GRADOS'], ondelete='CASCADE')
    op.drop_constraint(None, 'REPRE_EST', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'REPRE_EST', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('REPRE_EST_ID_EST_fkey'), 'REPRE_EST', 'ESTUDIANTES', ['ID_EST'], ['ID_EST'], ondelete='CASCADE')
    op.create_foreign_key(op.f('REPRE_EST_ID_REPRE_fkey'), 'REPRE_EST', 'REPRESENTANTES', ['ID_REPRE'], ['ID_REP'], ondelete='CASCADE')
    op.drop_constraint(None, 'PROFESORES', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('FK_PROFESORES_ROLES'), 'PROFESORES', 'ROLES', ['ID_ROL'], ['ID_ROL'], ondelete='CASCADE')
    op.drop_constraint(None, 'INCIDENCIAS', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'INCIDENCIAS', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('INCIDENCIAS_ID_EST_fkey'), 'INCIDENCIAS', 'ESTUDIANTES', ['ID_EST'], ['ID_EST'], ondelete='CASCADE')
    op.create_foreign_key(op.f('INCIDENCIAS_ID_PROF_fkey'), 'INCIDENCIAS', 'PROFESORES', ['ID_PROF'], ['ID_PROF'], ondelete='CASCADE')
    op.drop_constraint(None, 'CALIFICACIONES', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'CALIFICACIONES', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'CALIFICACIONES', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('CALIFICACIONES_ID_SECCION_fkey'), 'CALIFICACIONES', 'SECCIONES', ['ID_SECCION'], ['ID_SECCION'], ondelete='CASCADE')
    op.create_foreign_key(op.f('CALIFICACIONES_ID_MATERIA_fkey'), 'CALIFICACIONES', 'MATERIAS', ['ID_MATERIA'], ['ID_MATERIA'], ondelete='CASCADE')
    op.create_foreign_key(op.f('CALIFICACIONES_ID_EST_fkey'), 'CALIFICACIONES', 'ESTUDIANTES', ['ID_EST'], ['ID_EST'], ondelete='CASCADE')
    op.drop_constraint(None, 'ASISTENCIA_PROFESORES', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('ASISTENCIA_PROFESORES_ID_PROF_fkey'), 'ASISTENCIA_PROFESORES', 'PROFESORES', ['ID_PROF'], ['ID_PROF'], ondelete='CASCADE')
    op.drop_constraint(None, 'ASISTENCIA_ESTUDIANTES', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'ASISTENCIA_ESTUDIANTES', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('ASISTENCIA_ESTUDIANTES_ID_EST_fkey'), 'ASISTENCIA_ESTUDIANTES', 'ESTUDIANTES', ['ID_EST'], ['ID_EST'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('ASISTENCIA_ESTUDIANTES_ID_SECCION_fkey'), 'ASISTENCIA_ESTUDIANTES', 'SECCIONES', ['ID_SECCION'], ['ID_SECCION'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'ASIGNACION_EST', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'ASIGNACION_EST', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('ASIGNACION_EST_ID_EST_fkey'), 'ASIGNACION_EST', 'ESTUDIANTES', ['ID_EST'], ['ID_EST'], ondelete='CASCADE')
    op.create_foreign_key(op.f('ASIGNACION_EST_ID_SECCION_fkey'), 'ASIGNACION_EST', 'SECCIONES', ['ID_SECCION'], ['ID_SECCION'], ondelete='CASCADE')
    # ### end Alembic commands ###
